import { montserrat } from "@/lib/fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { IntlProvider } from "@/components/intl-provider";
import { getLocale, getMessages } from "next-intl/server";

export const metadata = {
  title: "Oracode",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased`}>
        <IntlProvider locale={locale} messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="bluewhite"
            enableSystem
          >
            {children}
          </ThemeProvider>
        </IntlProvider>
      </body>
    </html>
  );
}
